on: [push, pull_request]
name: Test

jobs:
  check:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check and Test 2
        env:
          RUST_TEST_THREADS: 8
          LOG_LEVEL: raft=error
        run: make test_2
